---
services:
  mysql:
    image: my-mysql:v1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
    ports:
      - "12345:3306"

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
