services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ../.env 
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
