CREATE DATABASE IF NOT EXISTS `${USERDB_DATABASE}`;
CREATE USER IF NOT EXISTS '${USERDB_USERNAME}'@'%' IDENTIFIED BY '${USERDB_PASSWORD}';
GRANT ALL PRIVILEGES ON `${USERDB_DATABASE}`.* TO '${USERDB_USERNAME}'@'%';

CREATE DATABASE IF NOT EXISTS `${RECIPEDB_DATABASE}`;
CREATE USER IF NOT EXISTS '${RECIPEDB_USERNAME}'@'%' IDENTIFIED BY '${RECIPEDB_PASSWORD}';
GRANT ALL PRIVILEGES ON `${RECIPEDB_DATABASE}`.* TO '${RECIPEDB_USERNAME}'@'%';