---
server:
  port: 8081

spring:
<<<<<<< HEAD
  config:
    import: optional:dotenv:env

  application:
    name: user-service
    
=======
  application:
    name: user-service

  profiles:
    include: dotenv

>>>>>>> 882638b38577b6d64d7af4d05aec0eac50b37214
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=UTC
    username: ${USERDB_USERNAME}
    password: ${USERDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org.springframework: INFO
    com.gazpacho.userservice: DEBUG
